services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:0.19.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
    volumes:
      - config:/config

volumes:
  config:

networks:
  default:
    external: true
    name: proxy
