services:
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:10.4.3
    restart: unless-stopped
    user: '0'
    volumes:
      - data:/var/lib/grafana

volumes:
  data:

networks:
  default:
    external: true
    name: proxy
