services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: mc-vanilla-1
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.6"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_INIT: "30"
      AUTOPAUSE_TIMEOUT_EST: "10"
      DEBUG_AUTOPAUSE: "true"
    volumes:
      - mc-vanilla-1_data:/data

volumes:
  mc-vanilla-1_data:
    name: mc-vanilla-1_data
    external: true

networks:
  default:
    external: true
    name: minecraft
