services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.13
    restart: unless-stopped
    volumes:
      - uptime-kuma:/app/data

volumes:
  uptime-kuma:
    name: uptime-kuma

networks:
  default:
    external: true
    name: proxy
