services:
  app:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:2.11.2
    restart: unless-stopped
    ports:
      - 80:80   # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81   # Admin Web Port
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
      
volumes:
  data:
  letsencrypt:
  
networks:
  default:
    external: true
    name: proxy
